[package]
name = "zk_transciphering"
version = "0.1.0"
edition = "2024"

[dependencies]
homomorphic.workspace = true
transciphering.workspace = true
tfhe.workspace = true
thiserror.workspace = true
ark-bls12-381.workspace = true
ark-ff.workspace = true
ark-groth16.workspace = true
ark-r1cs-std.workspace = true
ark-relations.workspace = true
ark-snark.workspace = true
ark-std.workspace = true
rand.workspace = true
symmetric.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "benchmarks"
harness = false
